# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: From Tonkin to India
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the text of <em>From Tonkin to India</em> by ["Orle패ans, Henri d'", 'Prince', '1867-1901', 'Prince', "Orle패ans, Henri d'", '1867-1901'], adapted from a British Library 
  electronic text.
baseurl: "" # the subpath of your site, e.g. /blog
book_id: "011836203"
url: "https://git-lit.github.io/011836203" 

about: > 
  This is an electronic text of <em>From Tonkin to India</em> by ["Orle패ans, Henri d'", 'Prince', '1867-1901', 'Prince', "Orle패ans, Henri d'", '1867-1901'], adapted from a British Library scan. Here is the British Library [catalog record](http://explore.bl.uk/primo_library/libweb/action/search.do?cs=frb&doc=BLL01011836203&dscnt=1&scp.scps=scope:(BLCONTENT)&frbg=&tab=local_tab&srt=rank&ct=search&mode=Basic&dum=true&tb=t&indx=1&vl(freeText0)=011836203&fn=search&vid=BLVU1). There may be illustrations from the volume available on [flickr](https://www.flickr.com/photos/britishlibrary/tags/sysnum011836203). There may be illustrations from the volume available on [flickr](https://www.flickr.com/photos/britishlibrary/tags/sysnum011836203).

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false